# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/users/Evan Konermann/documents/othello/Milestone_1"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/users/Evan Konermann/documents/othello/Milestone_1"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/users/Evan Konermann/documents/othello/Milestone_1/CMakeFiles" "/mnt/c/users/Evan Konermann/documents/othello/Milestone_1/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/users/Evan Konermann/documents/othello/Milestone_1/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named board_tests

# Build rule for target.
board_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 board_tests
.PHONY : board_tests

# fast build rule for target.
board_tests/fast:
	$(MAKE) -f CMakeFiles/board_tests.dir/build.make CMakeFiles/board_tests.dir/build
.PHONY : board_tests/fast

#=============================================================================
# Target rules for targets named board_demo

# Build rule for target.
board_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 board_demo
.PHONY : board_demo

# fast build rule for target.
board_demo/fast:
	$(MAKE) -f CMakeFiles/board_demo.dir/build.make CMakeFiles/board_demo.dir/build
.PHONY : board_demo/fast

#=============================================================================
# Target rules for targets named board_demo2

# Build rule for target.
board_demo2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 board_demo2
.PHONY : board_demo2

# fast build rule for target.
board_demo2/fast:
	$(MAKE) -f CMakeFiles/board_demo2.dir/build.make CMakeFiles/board_demo2.dir/build
.PHONY : board_demo2/fast

board.o: board.c.o

.PHONY : board.o

# target to build an object file
board.c.o:
	$(MAKE) -f CMakeFiles/board_tests.dir/build.make CMakeFiles/board_tests.dir/board.c.o
	$(MAKE) -f CMakeFiles/board_demo.dir/build.make CMakeFiles/board_demo.dir/board.c.o
	$(MAKE) -f CMakeFiles/board_demo2.dir/build.make CMakeFiles/board_demo2.dir/board.c.o
.PHONY : board.c.o

board.i: board.c.i

.PHONY : board.i

# target to preprocess a source file
board.c.i:
	$(MAKE) -f CMakeFiles/board_tests.dir/build.make CMakeFiles/board_tests.dir/board.c.i
	$(MAKE) -f CMakeFiles/board_demo.dir/build.make CMakeFiles/board_demo.dir/board.c.i
	$(MAKE) -f CMakeFiles/board_demo2.dir/build.make CMakeFiles/board_demo2.dir/board.c.i
.PHONY : board.c.i

board.s: board.c.s

.PHONY : board.s

# target to generate assembly for a file
board.c.s:
	$(MAKE) -f CMakeFiles/board_tests.dir/build.make CMakeFiles/board_tests.dir/board.c.s
	$(MAKE) -f CMakeFiles/board_demo.dir/build.make CMakeFiles/board_demo.dir/board.c.s
	$(MAKE) -f CMakeFiles/board_demo2.dir/build.make CMakeFiles/board_demo2.dir/board.c.s
.PHONY : board.c.s

board_demo.o: board_demo.c.o

.PHONY : board_demo.o

# target to build an object file
board_demo.c.o:
	$(MAKE) -f CMakeFiles/board_demo.dir/build.make CMakeFiles/board_demo.dir/board_demo.c.o
.PHONY : board_demo.c.o

board_demo.i: board_demo.c.i

.PHONY : board_demo.i

# target to preprocess a source file
board_demo.c.i:
	$(MAKE) -f CMakeFiles/board_demo.dir/build.make CMakeFiles/board_demo.dir/board_demo.c.i
.PHONY : board_demo.c.i

board_demo.s: board_demo.c.s

.PHONY : board_demo.s

# target to generate assembly for a file
board_demo.c.s:
	$(MAKE) -f CMakeFiles/board_demo.dir/build.make CMakeFiles/board_demo.dir/board_demo.c.s
.PHONY : board_demo.c.s

board_demo2.o: board_demo2.c.o

.PHONY : board_demo2.o

# target to build an object file
board_demo2.c.o:
	$(MAKE) -f CMakeFiles/board_demo2.dir/build.make CMakeFiles/board_demo2.dir/board_demo2.c.o
.PHONY : board_demo2.c.o

board_demo2.i: board_demo2.c.i

.PHONY : board_demo2.i

# target to preprocess a source file
board_demo2.c.i:
	$(MAKE) -f CMakeFiles/board_demo2.dir/build.make CMakeFiles/board_demo2.dir/board_demo2.c.i
.PHONY : board_demo2.c.i

board_demo2.s: board_demo2.c.s

.PHONY : board_demo2.s

# target to generate assembly for a file
board_demo2.c.s:
	$(MAKE) -f CMakeFiles/board_demo2.dir/build.make CMakeFiles/board_demo2.dir/board_demo2.c.s
.PHONY : board_demo2.c.s

board_tests.o: board_tests.cc.o

.PHONY : board_tests.o

# target to build an object file
board_tests.cc.o:
	$(MAKE) -f CMakeFiles/board_tests.dir/build.make CMakeFiles/board_tests.dir/board_tests.cc.o
.PHONY : board_tests.cc.o

board_tests.i: board_tests.cc.i

.PHONY : board_tests.i

# target to preprocess a source file
board_tests.cc.i:
	$(MAKE) -f CMakeFiles/board_tests.dir/build.make CMakeFiles/board_tests.dir/board_tests.cc.i
.PHONY : board_tests.cc.i

board_tests.s: board_tests.cc.s

.PHONY : board_tests.s

# target to generate assembly for a file
board_tests.cc.s:
	$(MAKE) -f CMakeFiles/board_tests.dir/build.make CMakeFiles/board_tests.dir/board_tests.cc.s
.PHONY : board_tests.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... board_tests"
	@echo "... board_demo"
	@echo "... board_demo2"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... board_demo.o"
	@echo "... board_demo.i"
	@echo "... board_demo.s"
	@echo "... board_demo2.o"
	@echo "... board_demo2.i"
	@echo "... board_demo2.s"
	@echo "... board_tests.o"
	@echo "... board_tests.i"
	@echo "... board_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

